# Generated by Django 5.1 on 2026-06-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('panel_cotizaciones', 'Panel: Cotizaciones — ver, asignar y gestionar estados'), ('panel_clientes', 'Panel: Clientes — ver perfiles e historial'), ('panel_tickets', 'Panel: Tickets — ver, crear y actualizar servicio'), ('panel_contratos', 'Panel: Contratos — ver lista de alquileres'), ('panel_insumos', 'Panel: Insumos — ver catálogo de consumibles')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
