# Generated by Django 5.1 on 2026-06-09 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('view_quote', 'Ver cotización'), ('update_quote', 'Actualizar cotización'), ('assign_quote', 'Asignarse cotización'), ('view_ticket', 'Ver ticket'), ('create_ticket', 'Crear ticket'), ('update_ticket', 'Actualizar ticket'), ('view_client', 'Ver cliente'), ('view_contract', 'Ver contrato'), ('view_consumables', 'Ver insumos'), ('search_consumables', 'Buscar insumos')], max_length=25)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('related_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad del panel',
                'verbose_name_plural': 'Actividades del panel',
                'ordering': ['-created_at'],
            },
        ),
    ]
