# Generated by Django 5.1 on 2026-06-24 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_panel_facturacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mensajero', 'Mensajero'), ('tecnico', 'Técnico')], max_length=15)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de campo',
                'verbose_name_plural': 'Usuarios de campo',
            },
        ),
        migrations.CreateModel(
            name='FieldUserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('is_on_shift', models.BooleanField(db_index=True, default=False)),
                ('battery', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación de campo',
                'verbose_name_plural': 'Ubicaciones de campo',
            },
        ),
    ]
