# Generated by Django 5.1 on 2026-06-24 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_field_user_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=10)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, verbose_name='notas de entrega')),
                ('completion_invoice', models.CharField(blank=True, max_length=100, verbose_name='# factura / remisión')),
                ('completion_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/%Y/%m/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_tasks', to=settings.AUTH_USER_MODEL)),
                ('field_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='dashboard.fielduser')),
            ],
            options={
                'verbose_name': 'Tarea de entrega',
                'verbose_name_plural': 'Tareas de entrega',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
