# Generated by Django 5.1.4 on 2026-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delivery_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='completion_signature',
            field=models.TextField(blank=True, verbose_name='firma del receptor'),
        ),
    ]
