# Generated by Django 5.1.4 on 2026-07-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_completion_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='completion_photo_b64',
            field=models.TextField(blank=True, verbose_name='foto de entrega (base64)'),
        ),
    ]
