# Generated by Django 5.1.4 on 2026-08-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_field_location_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fieldlocationlog',
            new_name='dashboard_f_user_id_cf1c91_idx',
            old_name='dashboard_f_user_id_shift_idx',
        ),
    ]
