# Generated by Django 5.1.4 on 2026-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_dashboard_f_user_id_shift_idx_dashboard_f_user_id_cf1c91_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=10, verbose_name='prioridad'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='task_type',
            field=models.CharField(choices=[('entrega', 'Entrega'), ('recoleccion', 'Recolección')], db_index=True, default='entrega', max_length=15, verbose_name='tipo de tarea'),
        ),
    ]
