# Generated by Django 5.1.4 on 2026-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_deliverytask_priority_deliverytask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='completion_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='fotos de entrega (base64)'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='completion_photo_b64',
            field=models.TextField(blank=True, verbose_name='foto de entrega (base64, legado — usar completion_photos)'),
        ),
    ]
