# Generated by Django 5.1.4 on 2026-09-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_deliverytask_completion_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_overdue', 'Tarea vencida'), ('contract_expiring', 'Contrato por vencer'), ('contract_renewal', 'Renovación de contrato'), ('new_quote', 'Nueva cotización'), ('quote_stale', 'Cotización sin atender'), ('lead_cold', 'Lead sin actividad'), ('task_assigned', 'Nueva tarea asignada'), ('delivery_done', 'Entrega/recolección completada'), ('ticket_status', 'Ticket actualizado por técnico')], max_length=25),
        ),
    ]
