# Generated by Django 5.1.4 on 2026-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('view_quote', 'Ver cotización'), ('update_quote', 'Actualizar cotización'), ('assign_quote', 'Asignarse cotización'), ('view_ticket', 'Ver ticket'), ('create_ticket', 'Crear ticket'), ('update_ticket', 'Actualizar ticket'), ('view_client', 'Ver cliente'), ('create_client', 'Crear cliente'), ('view_contract', 'Ver contrato'), ('view_consumables', 'Ver insumos'), ('search_consumables', 'Buscar insumos')], max_length=25),
        ),
    ]
