# Generated by Django 5.1.4 on 2026-09-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_employeeactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielduserlocation',
            name='is_on_lunch',
            field=models.BooleanField(db_index=True, default=False, verbose_name='en almuerzo'),
        ),
        migrations.AddField(
            model_name='fielduserlocation',
            name='lunch_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='almuerzo iniciado'),
        ),
    ]
