# Generated by Django 5.1.4 on 2026-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielduserlocation',
            name='lunch_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha del acumulado de almuerzo'),
        ),
        migrations.AddField(
            model_name='fielduserlocation',
            name='lunch_seconds_used',
            field=models.PositiveIntegerField(default=0, verbose_name='segundos de almuerzo usados hoy'),
        ),
    ]
