# Generated by Django 5.1.4 on 2026-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_fielduserlocation_lunch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('cxc', 'CXC'), ('cxp', 'CXP')], max_length=20, verbose_name='método de pago'),
        ),
    ]
