# Generated by Django 5.1.4 on 2026-09-11 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerCashBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='fecha')),
                ('given', models.BooleanField(default=False, verbose_name='se le dio base')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor de la base')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_bases', to='dashboard.fielduser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base de mensajero',
                'verbose_name_plural': 'Bases de mensajeros',
                'ordering': ['-date'],
                'unique_together': {('field_user', 'date')},
            },
        ),
    ]
