# Generated by Django 5.1.4 on 2026-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_b64',
            field=models.TextField(blank=True, verbose_name='nota de voz'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='photo_b64',
            field=models.TextField(blank=True, verbose_name='foto adjunta'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, verbose_name='mensaje'),
        ),
    ]
