# Generated by Django 5.1.4 on 2026-09-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='completion_cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='efectivo recibido'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='completion_transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='transferencia recibida'),
        ),
    ]
