# Generated by Django 5.1.4 on 2026-09-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_fieldshiftlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_overdue', 'Tarea vencida'), ('contract_expiring', 'Contrato por vencer'), ('contract_renewal', 'Renovación de contrato'), ('new_quote', 'Nueva cotización'), ('quote_stale', 'Cotización sin atender'), ('lead_cold', 'Lead sin actividad'), ('task_assigned', 'Nueva tarea asignada'), ('delivery_done', 'Entrega/recolección completada'), ('ticket_status', 'Ticket actualizado por técnico'), ('ticket_arrival', 'Llegada a sitio'), ('ticket_departure', 'Salida de sitio'), ('lunch_break', 'Almuerzo'), ('chat_message', 'Mensaje de chat'), ('personal_task', 'Recordatorio personal')], max_length=25),
        ),
        migrations.CreateModel(
            name='PersonalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('due_date', models.DateField(verbose_name='fecha')),
                ('is_done', models.BooleanField(db_index=True, default=False, verbose_name='completada')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='completada el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea personal',
                'verbose_name_plural': 'Tareas personales',
                'ordering': ['is_done', 'due_date'],
                'indexes': [models.Index(fields=['user', 'is_done', 'due_date'], name='dashboard_p_user_id_4965fe_idx')],
            },
        ),
    ]
