# Generated by Django 5.1.4 on 2026-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_fielduserlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Lista de {name, type, data} -- documentos que no son fotos (PDF, Word, etc.)', verbose_name='archivos adjuntos'),
        ),
    ]
