# Generated by Django 5.1.4 on 2026-07-17 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0012_rentalcontract_unit_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('color', models.CharField(default='#3B82F6', help_text='Código hex, ej: #3B82F6', max_length=7, verbose_name='color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_labels', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'Etiqueta de conversación',
                'verbose_name_plural': 'Etiquetas de conversación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='teléfono WA')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='nombre del contacto')),
                ('wa_contact_id', models.CharField(blank=True, help_text='ID interno de Meta — se completa con API real', max_length=100, verbose_name='WA contact ID')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('open', 'Abierta'), ('pending', 'Pendiente'), ('resolved', 'Resuelta'), ('spam', 'Spam')], db_index=True, default='new', max_length=15, verbose_name='estado')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='último mensaje')),
                ('last_message_preview', models.CharField(blank=True, max_length=200, verbose_name='preview')),
                ('unread_count', models.PositiveSmallIntegerField(default=0, verbose_name='sin leer')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_conversations', to=settings.AUTH_USER_MODEL, verbose_name='asesora asignada')),
                ('labels', models.ManyToManyField(blank=True, to='whatsapp.conversationlabel', verbose_name='etiquetas')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_conversations', to='leads.lead', verbose_name='cliente CRM')),
            ],
            options={
                'verbose_name': 'Conversación WhatsApp',
                'verbose_name_plural': 'Conversaciones WhatsApp',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], default='inbound', max_length=10, verbose_name='dirección')),
                ('wa_message_id', models.CharField(blank=True, help_text='ID de Meta — vacío en modo prototipo', max_length=100, verbose_name='WA message ID')),
                ('body', models.TextField(blank=True, verbose_name='texto')),
                ('media_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('sticker', 'Sticker')], default='text', max_length=12, verbose_name='tipo')),
                ('media_url', models.CharField(blank=True, max_length=500, verbose_name='URL de archivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='sent', max_length=12, verbose_name='estado')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation', verbose_name='conversación')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['created_at'],
            },
        ),
    ]
