# Generated by Django 5.1.4 on 2026-09-17 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('title', models.CharField(help_text='Texto corto del botón, ej: Horario de atención', max_length=60, verbose_name='título')),
                ('body', models.TextField(help_text='Texto que se inserta en la respuesta al hacer clic', verbose_name='mensaje')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_quick_replies', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'Respuesta rápida',
                'verbose_name_plural': 'Respuestas rápidas',
                'ordering': ['order', 'title'],
            },
        ),
    ]
