# Generated by Django 5.1.4 on 2026-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_quickreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('ai_assist_enabled', models.BooleanField(default=False, help_text='Si está activo, aparece el botón «Sugerir respuesta» en las conversaciones.', verbose_name='asistente IA activo')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuración WhatsApp',
            },
        ),
    ]
