# Generated by Django 5.1.4 on 2026-05-22 03:21

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('site_name', models.CharField(max_length=100, verbose_name='nombre del sitio')),
                ('tagline', models.CharField(max_length=200, verbose_name='tagline')),
                ('default_meta_description', models.CharField(max_length=170, verbose_name='meta description por defecto')),
                ('default_og_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='seo/defaults/')),
                ('phone_primary', models.CharField(max_length=30, verbose_name='teléfono principal')),
                ('phone_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='email de contacto')),
                ('email_sales', models.EmailField(max_length=254, verbose_name='email de ventas')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('city', models.CharField(default='Medellín', max_length=80, verbose_name='ciudad')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps URL')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=10, verbose_name='estado')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='publicado el')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='destacado')),
                ('author_name', models.CharField(max_length=120, verbose_name='nombre del cliente')),
                ('author_role', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('author_company', models.CharField(blank=True, max_length=120, verbose_name='empresa')),
                ('author_photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='testimonials/')),
                ('quote', models.TextField(verbose_name='testimonio')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='calificación')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
