# Generated by Django 5.1.4 on 2026-05-22 03:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=30, verbose_name='teléfono')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201+', 'Más de 200 empleados')], max_length=10)),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('city', models.CharField(default='Medellín', max_length=80, verbose_name='ciudad')),
                ('source', models.CharField(choices=[('wizard', 'Cotizador interactivo'), ('contact', 'Formulario de contacto'), ('whatsapp', 'WhatsApp'), ('phone', 'Llamada telefónica'), ('referral', 'Referido')], default='wizard', max_length=20)),
                ('notes_internal', models.TextField(blank=True, verbose_name='notas internas')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='consentimiento GDPR')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'), models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interest_area', models.CharField(choices=[('rental', 'Alquiler de fotocopiadoras'), ('sale', 'Compra de fotocopiadoras'), ('cabling', 'Cableado estructurado'), ('software', 'Desarrollo de software'), ('web', 'Diseño web'), ('mobile', 'App móvil'), ('database', 'Base de datos'), ('full_office', 'Solución integral de oficina')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('reviewing', 'En revisión'), ('sent', 'Enviada al cliente'), ('won', 'Ganada'), ('lost', 'Perdida')], db_index=True, default='new', max_length=15)),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('wizard_data', models.JSONField(blank=True, default=dict)),
                ('client_message', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leads.quote')),
            ],
            options={
                'verbose_name': 'Ítem de cotización',
                'verbose_name_plural': 'Ítems de cotización',
            },
        ),
    ]
