# Generated by Django 5.1.4 on 2026-06-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='interest_area',
            field=models.CharField(choices=[('rental', 'Alquiler de fotocopiadoras'), ('sale', 'Compra de fotocopiadoras'), ('consumables', 'Tóner, tintas y repuestos'), ('cabling', 'Cableado estructurado'), ('software', 'Desarrollo de software'), ('web', 'Diseño web'), ('mobile', 'App móvil'), ('database', 'Base de datos'), ('full_office', 'Solución integral de oficina')], max_length=20),
        ),
    ]
