# Generated by Django 5.1 on 2026-06-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_consumable_featured_prices'),
        ('leads', '0002_add_consumables_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('equipment_description', models.CharField(help_text='Marca, modelo y serial del equipo entregado.', max_length=300, verbose_name='descripción del equipo')),
                ('contract_number', models.CharField(max_length=30, unique=True, verbose_name='número de contrato')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de firma'), ('active', 'Activo'), ('expired', 'Vencido'), ('cancelled', 'Cancelado')], db_index=True, default='active', max_length=15, verbose_name='estado')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cuota mensual')),
                ('copies_included', models.PositiveIntegerField(default=0, verbose_name='copias incluidas/mes')),
                ('copy_overage_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='precio copia excedente')),
                ('notes', models.TextField(blank=True, verbose_name='notas / condiciones')),
                ('copier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_contracts', to='catalog.copier', verbose_name='fotocopiadora')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='leads.lead', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Contrato de alquiler',
                'verbose_name_plural': 'Contratos de alquiler',
                'ordering': ['-created_at'],
            },
        ),
    ]
