# Generated by Django 5.1 on 2026-06-09 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rental_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('ticket_number', models.CharField(max_length=30, unique=True, verbose_name='número de ticket')),
                ('equipment_description', models.CharField(blank=True, max_length=300, verbose_name='equipo')),
                ('issue_type', models.CharField(choices=[('maintenance', 'Mantenimiento preventivo'), ('repair', 'Reparación / avería'), ('installation', 'Instalación'), ('calibration', 'Calibración'), ('supply', 'Suministro de insumos'), ('other', 'Otro')], default='repair', max_length=20, verbose_name='tipo de servicio')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=10, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En proceso'), ('waiting_parts', 'Esperando repuestos'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=20, verbose_name='estado')),
                ('description', models.TextField(verbose_name='descripción del problema')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='notas de resolución')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='visita programada')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelto el')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='técnico asignado')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='leads.rentalcontract', verbose_name='contrato relacionado')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='leads.lead', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Ticket de servicio',
                'verbose_name_plural': 'Tickets de servicio',
                'ordering': ['-created_at'],
            },
        ),
    ]
