# Generated by Django 5.1 on 2026-06-10 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_service_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cerrada el'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lost_reason',
            field=models.TextField(blank=True, verbose_name='motivo de pérdida'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('subject', models.CharField(max_length=300, verbose_name='asunto')),
                ('recipient', models.EmailField(max_length=254, verbose_name='destinatario')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Error')], default='sent', max_length=10)),
                ('error_msg', models.TextField(blank=True, verbose_name='error')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='leads.lead', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Log de email',
                'verbose_name_plural': 'Log de emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('due_date', models.DateField(verbose_name='fecha límite')),
                ('description', models.TextField(verbose_name='descripción de la tarea')),
                ('is_done', models.BooleanField(db_index=True, default=False, verbose_name='completada')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='completada el')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Tarea de seguimiento',
                'verbose_name_plural': 'Tareas de seguimiento',
                'ordering': ['is_done', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('activity_type', models.CharField(choices=[('call', 'Llamada telefónica'), ('email', 'Email'), ('meeting', 'Reunión presencial'), ('note', 'Nota interna'), ('whatsapp', 'WhatsApp'), ('visit', 'Visita comercial')], default='note', max_length=20, verbose_name='tipo')),
                ('notes', models.TextField(verbose_name='descripción')),
                ('outcome', models.CharField(blank=True, max_length=300, verbose_name='resultado / próximo paso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades del lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
