# Generated by Django 5.1 on 2026-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_crm_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='nit',
            field=models.CharField(blank=True, db_index=True, max_length=25, verbose_name='NIT / Cédula'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('wizard', 'Cotizador interactivo'), ('contact', 'Formulario de contacto'), ('whatsapp', 'WhatsApp'), ('phone', 'Llamada telefónica'), ('referral', 'Referido'), ('import', 'Base de datos importada')], default='wizard', max_length=20),
        ),
    ]
