# Generated by Django 5.1 on 2026-06-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_add_nit_import_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='lead score'),
        ),
        migrations.AddField(
            model_name='lead',
            name='score_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='score calculado el'),
        ),
    ]
