# Generated by Django 5.1 on 2026-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_add_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='lost_category',
            field=models.CharField(blank=True, choices=[('price', 'Precio muy alto'), ('competitor', 'Eligió a la competencia'), ('no_budget', 'Sin presupuesto'), ('timing', 'Mal momento / pospuso'), ('no_need', 'Ya no necesita el servicio'), ('no_contact', 'Perdió contacto / no respondió'), ('other', 'Otro motivo')], db_index=True, max_length=15, verbose_name='categoría de pérdida'),
        ),
    ]
