# Generated by Django 5.1 on 2026-06-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_add_lost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='close_probability',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100 %. Se actualiza al mover en el pipeline.', verbose_name='probabilidad de cierre (%)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas internas'),
        ),
    ]
