# Generated by Django 5.1 on 2026-06-15 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_add_close_probability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('reading_date', models.DateField(verbose_name='fecha de lectura')),
                ('previous_reading', models.PositiveIntegerField(default=0, verbose_name='lectura anterior')),
                ('current_reading', models.PositiveIntegerField(verbose_name='lectura actual')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='leads.rentalcontract', verbose_name='contrato')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Lectura de contador',
                'verbose_name_plural': 'Lecturas de contador',
                'ordering': ['-reading_date'],
                'unique_together': {('contract', 'reading_date')},
            },
        ),
    ]
