# Generated by Django 5.1.4 on 2026-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_meter_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='dirección de visita'),
        ),
    ]
