# Generated by Django 5.1.4 on 2026-07-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_copier_unit'),
        ('leads', '0011_serviceticket_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unidad específica entregada al cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_contracts', to='catalog.copierunit', verbose_name='unidad física (serial)'),
        ),
    ]
