# Generated by Django 5.1.4 on 2026-09-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_rentalcontract_unit_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='leads.lead'),
        ),
    ]
