# Generated by Django 5.1.4 on 2026-09-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_quote_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='orden de ejecución'),
        ),
    ]
