# Generated by Django 5.1.4 on 2026-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_serviceticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('wizard', 'Cotizador interactivo'), ('contact', 'Formulario de contacto'), ('whatsapp', 'WhatsApp'), ('phone', 'Llamada telefónica'), ('referral', 'Referido'), ('import', 'Base de datos importada'), ('manual', 'Agregado manualmente')], default='wizard', max_length=20),
        ),
    ]
