# Generated by Django 5.1.4 on 2026-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='issue_type',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('renta', 'Renta'), ('remoto', 'Remoto'), ('cotizacion', 'Cotización'), ('instalacion', 'Instalación'), ('garantia', 'Garantía'), ('redes', 'Redes'), ('software', 'Software')], default='correctivo', max_length=20, verbose_name='tipo de servicio'),
        ),
    ]
