# Generated by Django 5.1.4 on 2026-09-09 20:22

from django.db import migrations

OLD_TO_NEW = {
    "maintenance": "mantenimiento",
    "repair": "correctivo",
    "installation": "instalacion",
    "calibration": "preventivo",
    "supply": "mantenimiento",
    "other": "mantenimiento",
}


def forwards(apps, schema_editor):
    ServiceTicket = apps.get_model("leads", "ServiceTicket")
    for old, new in OLD_TO_NEW.items():
        ServiceTicket.objects.filter(issue_type=old).update(issue_type=new)


def backwards(apps, schema_editor):
    ServiceTicket = apps.get_model("leads", "ServiceTicket")
    for old, new in OLD_TO_NEW.items():
        ServiceTicket.objects.filter(issue_type=new).update(issue_type=old)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_serviceticket_issue_type'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
