# Generated by Django 5.1.4 on 2026-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_remap_serviceticket_issue_type_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cxc', 'CXC'), ('efectivo', 'Efectivo'), ('na', 'N/A')], default='na', max_length=10, verbose_name='método de pago'),
        ),
    ]
