# Generated by Django 5.1.4 on 2026-09-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_serviceticket_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='llegada al sitio'),
        ),
    ]
