# Generated by Django 5.1.4 on 2026-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_serviceticket_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='evidence_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='fotos de evidencia (base64)'),
        ),
    ]
