# Generated by Django 5.1.4 on 2026-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_serviceticket_evidence_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En proceso'), ('waiting_parts', 'Esperando repuestos'), ('waiting_quote', 'Pendiente por cotización'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=20, verbose_name='estado'),
        ),
    ]
