# Generated by Django 5.1.4 on 2026-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_serviceticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='salida del sitio'),
        ),
    ]
