# Generated by Django 5.1.4 on 2026-09-15 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_copier_unit'),
        ('leads', '0023_serviceticket_departed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Para la hoja de vida del equipo. Si no se indica y el ticket tiene contrato, se toma del equipo del contrato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='catalog.copierunit', verbose_name='equipo (unidad física)'),
        ),
    ]
