# Generated by Django 5.1.4 on 2026-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_serviceticket_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cxc', 'CXC'), ('efectivo', 'Efectivo'), ('banco', 'Banco'), ('addi', 'Addi'), ('na', 'N/A')], default='na', max_length=10, verbose_name='método de pago'),
        ),
    ]
