# Generated by Django 5.1.4 on 2026-09-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_serviceticket_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='número de factura'),
        ),
    ]
