# Generated by Django 5.1.4 on 2026-05-22 03:21

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('slug', models.SlugField(help_text='Se genera automáticamente desde el nombre si se deja vacío.', max_length=220, unique=True, verbose_name='slug')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='título SEO')),
                ('meta_description', models.CharField(blank=True, max_length=170, verbose_name='descripción SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='keywords SEO')),
                ('og_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='imagen Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL canónica')),
                ('schema_type', models.CharField(choices=[('Product', 'Producto'), ('Service', 'Servicio'), ('Article', 'Artículo'), ('Organization', 'Organización'), ('WebPage', 'Página web genérica'), ('FAQPage', 'Página de preguntas frecuentes')], default='WebPage', max_length=30, verbose_name='tipo de schema.org')),
                ('noindex', models.BooleanField(default=False, verbose_name='excluir de buscadores')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('silo', models.CharField(choices=[('hardware', 'Hardware / Infraestructura'), ('software', 'Software / Digital'), ('general', 'General')], default='general', max_length=20)),
            ],
            options={
                'verbose_name': 'Categoría del blog',
                'verbose_name_plural': 'Categorías del blog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('slug', models.SlugField(help_text='Se genera automáticamente desde el nombre si se deja vacío.', max_length=220, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('slug', models.SlugField(help_text='Se genera automáticamente desde el nombre si se deja vacío.', max_length=220, unique=True, verbose_name='slug')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='título SEO')),
                ('meta_description', models.CharField(blank=True, max_length=170, verbose_name='descripción SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='keywords SEO')),
                ('og_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='imagen Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL canónica')),
                ('schema_type', models.CharField(choices=[('Product', 'Producto'), ('Service', 'Servicio'), ('Article', 'Artículo'), ('Organization', 'Organización'), ('WebPage', 'Página web genérica'), ('FAQPage', 'Página de preguntas frecuentes')], default='WebPage', max_length=30, verbose_name='tipo de schema.org')),
                ('noindex', models.BooleanField(default=False, verbose_name='excluir de buscadores')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=10, verbose_name='estado')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='publicado el')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='destacado')),
                ('main_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='content/originals/', verbose_name='imagen principal')),
                ('main_image_alt', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(max_length=300, verbose_name='resumen')),
                ('content', models.TextField(verbose_name='contenido completo')),
                ('reading_time_min', models.PositiveSmallIntegerField(default=5, verbose_name='tiempo de lectura')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'), models.Index(fields=['category', 'status'], name='blog_post_categor_4ee4b9_idx')],
            },
        ),
    ]
