# Generated by Django 5.1 on 2026-06-23 17:22

import apps.payments.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_copier_unit'),
        ('leads', '0010_meter_reading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('invoice_type', models.CharField(choices=[('FV', 'Factura de Venta'), ('NC', 'Nota Crédito'), ('ND', 'Nota Débito')], default='FV', max_length=2)),
                ('dian_resolution', models.CharField(blank=True, max_length=50, verbose_name='resolución DIAN')),
                ('dian_prefix', models.CharField(blank=True, default='FV', max_length=10, verbose_name='prefijo')),
                ('dian_consecutive', models.PositiveIntegerField(default=0, verbose_name='consecutivo')),
                ('cufe', models.CharField(blank=True, max_length=200, verbose_name='CUFE')),
                ('qr_url', models.URLField(blank=True, verbose_name='URL QR DIAN')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitida'), ('sent', 'Enviada al cliente'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('voided', 'Anulada')], db_index=True, default='draft', max_length=8)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='fecha de pago')),
                ('issuer_name', models.CharField(default='Solution Copiers', max_length=200, verbose_name='nombre emisor')),
                ('issuer_nit', models.CharField(blank=True, max_length=20, verbose_name='NIT emisor')),
                ('issuer_address', models.CharField(blank=True, max_length=300, verbose_name='dirección emisor')),
                ('issuer_city', models.CharField(default='Medellín', max_length=80, verbose_name='ciudad emisor')),
                ('issuer_email', models.EmailField(blank=True, max_length=254, verbose_name='email emisor')),
                ('issuer_phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono emisor')),
                ('issuer_tax_regime', models.CharField(blank=True, default='Responsable de IVA', max_length=60, verbose_name='régimen tributario')),
                ('client_name', models.CharField(max_length=200, verbose_name='nombre cliente')),
                ('client_nit', models.CharField(blank=True, max_length=25, verbose_name='NIT / Cédula cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='email cliente')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono cliente')),
                ('client_address', models.CharField(blank=True, max_length=300, verbose_name='dirección cliente')),
                ('client_city', models.CharField(blank=True, max_length=80, verbose_name='ciudad cliente')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='descuento')),
                ('tax_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='base gravable')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA (19%)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('payment_method', models.CharField(choices=[('10', 'Efectivo'), ('42', 'Transferencia bancaria'), ('48', 'Tarjeta de crédito/débito'), ('49', 'Pasarela electrónica (Wompi)'), ('20', 'Cheque')], default='49', max_length=2)),
                ('payment_notes', models.TextField(blank=True, verbose_name='notas de pago')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='leads.lead', verbose_name='cliente CRM')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date', '-dian_consecutive'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='cantidad')),
                ('unit', models.CharField(default='UND', max_length=30, verbose_name='unidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='precio unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='descuento %')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.19'), max_digits=5, verbose_name='tasa IVA')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='catalog.consumable')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.invoice')),
            ],
            options={
                'verbose_name': 'Línea de factura',
                'verbose_name_plural': 'Líneas de factura',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('reference', models.CharField(db_index=True, default=apps.payments.models._order_ref, max_length=20, unique=True, verbose_name='referencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('failed', 'Pago fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], db_index=True, default='pending', max_length=12)),
                ('buyer_name', models.CharField(max_length=150, verbose_name='nombre del comprador')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='email')),
                ('buyer_phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('buyer_nit', models.CharField(blank=True, max_length=25, verbose_name='NIT / Cédula')),
                ('buyer_company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('buyer_city', models.CharField(default='Medellín', max_length=80, verbose_name='ciudad')),
                ('buyer_address', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='leads.lead', verbose_name='lead CRM')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='payments.order', verbose_name='pedido origen'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('product_name', models.CharField(max_length=200, verbose_name='nombre del producto')),
                ('part_number', models.CharField(blank=True, max_length=80, verbose_name='referencia')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.consumable')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('wompi_id', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ID transacción Wompi')),
                ('reference', models.CharField(db_index=True, max_length=30, verbose_name='referencia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado'), ('VOIDED', 'Anulado'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=10)),
                ('amount_in_cents', models.PositiveBigIntegerField(verbose_name='monto en centavos')),
                ('currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('payment_method_type', models.CharField(blank=True, max_length=30, verbose_name='método Wompi')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='marca tarjeta')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='últimos 4 dígitos')),
                ('bank_name', models.CharField(blank=True, max_length=80, verbose_name='banco PSE')),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True, verbose_name='webhook recibido')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload Wompi')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='payments_or_status_99bb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='payments_in_status_87aab9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client_nit'], name='payments_in_client__885089_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
    ]
