# Generated by Django 5.1 on 2026-06-24 02:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='net_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='neto recibido'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_fuente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='RteFuente aplicada'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_fuente_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='tarifa RteFuente %'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_ica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ReteICA aplicada'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_ica_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='tarifa ReteICA ‰'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ReteIVA aplicada'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_iva_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='tarifa ReteIVA %'),
        ),
    ]
