# Generated by Django 5.1.4 on 2026-07-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_net_received_invoice_retention_fuente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stock_reduced',
            field=models.BooleanField(default=False, verbose_name='stock descontado'),
        ),
    ]
