# Generated by Django 5.1.4 on 2026-05-22 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(default='Solution Copiers Corporate', max_length=80, verbose_name='nombre del tema')),
                ('color_primary', models.CharField(default='#C4121A', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='color primario (Rojo intenso)')),
                ('color_primary_dark', models.CharField(default='#5A0B0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='primario oscuro (Vinotinto)')),
                ('color_primary_light', models.CharField(default='#8E1B1B', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='primario claro (Rojo oscuro)')),
                ('color_accent', models.CharField(default='#8E1B1B', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='color de acento')),
                ('color_accent_dark', models.CharField(default='#5A0B0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='acento oscuro')),
                ('color_success', models.CharField(default='#2E7D32', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('color_warning', models.CharField(default='#E89A3C', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('color_danger', models.CharField(default='#C4121A', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('color_bg', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='fondo principal')),
                ('color_bg_alt', models.CharField(default='#D9D9D9', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='fondo alternativo')),
                ('color_surface', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='superficie de cards')),
                ('color_text_primary', models.CharField(default='#5A0B0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto principal')),
                ('color_text_secondary', models.CharField(default='#8A8A8A', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto secundario')),
                ('color_text_muted', models.CharField(default='#B0B0B0', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto atenuado')),
                ('color_border', models.CharField(default='#D9D9D9', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='bordes')),
                ('font_display', models.CharField(default="'Fraunces', Georgia, serif", max_length=100, verbose_name='fuente display')),
                ('font_body', models.CharField(default="'Inter', system-ui, sans-serif", max_length=100, verbose_name='fuente cuerpo')),
                ('font_mono', models.CharField(default="'JetBrains Mono', 'Fira Code', monospace", max_length=100, verbose_name='fuente monoespaciada')),
                ('google_fonts_url', models.URLField(blank=True, default='https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Inter:wght@400;500;600;700&display=swap', verbose_name='URL de Google Fonts')),
                ('spacing_base', models.PositiveSmallIntegerField(default=4, verbose_name='unidad base de spacing (px)')),
                ('border_radius_base', models.PositiveSmallIntegerField(default=12, verbose_name='radio borde base')),
                ('border_radius_lg', models.PositiveSmallIntegerField(default=24, verbose_name='radio grande')),
                ('glass_blur_amount', models.PositiveSmallIntegerField(default=16, verbose_name='intensidad blur')),
                ('glass_opacity', models.DecimalField(decimal_places=2, default=0.7, max_digits=3, verbose_name='opacidad cristal')),
                ('shadow_card', models.CharField(default='0 4px 24px -8px rgba(90, 11, 11, 0.10)', max_length=200)),
                ('shadow_card_hover', models.CharField(default='0 12px 40px -8px rgba(196, 18, 26, 0.20)', max_length=200)),
                ('animations_enabled', models.BooleanField(default=True, verbose_name='animaciones activas')),
                ('animation_duration_base', models.DecimalField(decimal_places=2, default=0.6, max_digits=3)),
                ('parallax_enabled', models.BooleanField(default=True, verbose_name='parallax activo')),
                ('smooth_scroll_enabled', models.BooleanField(default=True, verbose_name='smooth scroll')),
            ],
            options={
                'verbose_name': 'Design Tokens',
                'verbose_name_plural': 'Design Tokens',
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('old_path', models.CharField(max_length=500, unique=True, verbose_name='ruta antigua')),
                ('new_path', models.CharField(max_length=500, verbose_name='ruta nueva')),
                ('redirect_type', models.IntegerField(choices=[(301, '301 Permanente'), (302, '302 Temporal')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Regla de redirección',
                'verbose_name_plural': 'Reglas de redirección',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['old_path', 'is_active'], name='seo_redirec_old_pat_36641a_idx')],
            },
        ),
    ]
