# Generated by Django 5.1.4 on 2026-07-01 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtokens',
            name='color_accent',
            field=models.CharField(default='#C47A0A', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='color de acento (Dorado cálido)'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='color_accent_dark',
            field=models.CharField(default='#9A5E06', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='acento oscuro'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='color_bg_alt',
            field=models.CharField(default='#FBF5F5', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='fondo alternativo'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='color_border',
            field=models.CharField(default='#EDD5D5', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='bordes'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='color_primary_light',
            field=models.CharField(default='#D94048', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='primario claro (Rojo medio)'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='color_text_muted',
            field=models.CharField(default='#9C8080', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto atenuado'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='color_text_primary',
            field=models.CharField(default='#1C0B0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto principal'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='color_text_secondary',
            field=models.CharField(default='#6B5252', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color HEX válido (ej: #1A2B3C).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto secundario'),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='shadow_card',
            field=models.CharField(default='0 1px 3px rgba(28, 11, 11, 0.06), 0 4px 20px rgba(28, 11, 11, 0.07)', max_length=200),
        ),
        migrations.AlterField(
            model_name='designtokens',
            name='shadow_card_hover',
            field=models.CharField(default='0 4px 8px rgba(28, 11, 11, 0.08), 0 16px 40px rgba(196, 18, 26, 0.14)', max_length=200),
        ),
    ]
