# Generated by Django 5.1.4 on 2026-06-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='destacado'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='price_business',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio empresa (nivel 2)'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='price_on_request',
            field=models.BooleanField(default=False, verbose_name='precio bajo solicitud'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='price_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio mayorista (nivel 3)'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='descripción corta'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='brand',
            field=models.CharField(default='Ricoh', max_length=60, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_type',
            field=models.CharField(choices=[('toner_bn', 'Tóner B/N'), ('toner_color', 'Tóner Color'), ('ink', 'Tinta / Botella'), ('drum', 'Tambor / Cilindro'), ('fuser', 'Banda fusora / Fusor'), ('developer', 'Revelador'), ('roller', 'Rodillo'), ('blade', 'Cuchilla'), ('chip', 'Chip'), ('kit', 'Kit de mantenimiento'), ('other', 'Otro repuesto')], default='toner_bn', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='en stock'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='código / referencia'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio público (nivel 1)'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='yield_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='rendimiento (páginas)'),
        ),
    ]
