# Generated by Django 5.1 on 2026-06-09 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_consumable_featured_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad en stock'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjustment', 'Ajuste manual')], max_length=15, verbose_name='tipo')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.consumable', verbose_name='consumible')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
