# Generated by Django 5.1 on 2026-06-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stock_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopierUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('serial_number', models.CharField(max_length=80, unique=True, verbose_name='serial')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_field', 'En campo (cliente)'), ('maintenance', 'En mantenimiento'), ('retired', 'Dado de baja')], db_index=True, default='available', max_length=15, verbose_name='estado')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('excellent', 'Excelente'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Deteriorado')], default='good', max_length=15, verbose_name='condición')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('location_notes', models.CharField(blank=True, max_length=300, verbose_name='ubicación / notas')),
                ('current_meter', models.PositiveIntegerField(default=0, help_text='Último contador conocido del equipo.', verbose_name='contador actual (páginas)')),
                ('copier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='catalog.copier', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'Unidad de equipo',
                'verbose_name_plural': 'Unidades de equipos',
                'ordering': ['status', 'copier__brand', 'serial_number'],
            },
        ),
    ]
