# Generated by Django 5.1.4 on 2026-09-15 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_copier_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopierUnitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('date', models.DateField(verbose_name='fecha')),
                ('note', models.TextField(verbose_name='nota')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copier_unit_notes', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='catalog.copierunit', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'Nota de hoja de vida',
                'verbose_name_plural': 'Notas de hoja de vida',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
