# Generated by Django 5.1.4 on 2026-05-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('tipo_servicio', models.CharField(choices=[('venta', 'Venta de equipos'), ('alquiler', 'Alquiler de equipos'), ('mantenimiento', 'Mantenimiento'), ('suministros', 'Suministros / Tóner'), ('soporte', 'Soporte técnico'), ('software', 'Software / Desarrollo'), ('cableado', 'Cableado estructurado')], max_length=50, verbose_name='Tipo de servicio recibido')),
                ('calificacion_atencion', models.PositiveSmallIntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], verbose_name='Calidad de atención')),
                ('calificacion_servicio', models.PositiveSmallIntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], verbose_name='Calidad del servicio técnico')),
                ('calificacion_tiempo', models.PositiveSmallIntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], verbose_name='Tiempo de respuesta')),
                ('calificacion_precio', models.PositiveSmallIntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], verbose_name='Relación precio / calidad')),
                ('recomendaria', models.BooleanField(default=True, verbose_name='¿Recomendaría Solution Copiers?')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha'],
            },
        ),
    ]
